package com.example.controllers;


/*import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.example.models.User;
import com.example.repository.UserRepository;

@RestController    // This means that this class is a Controller
public class UserController {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private UserRepository repository;

	@RequestMapping("/save")
    public String process(){
		repository.save(new User("Jack", "jack.123","jack@gmail.com"));
		repository.save(new User("Chloe", "chloe.345","chloe123@gmail.com"));
		repository.save(new User("Kim", "samsung43","kim@hotmail.com"));
		repository.save(new User("David", "victoria89","david56@hotmail.com"));
		repository.save(new User("Michelle", "john500","michelle_m@gmail.com"));
        return "Done";
    }
       
       
    @RequestMapping("/findall")
    public String findAll(){
        String result = "<html>";
           
        for(User user : repository.findAll()){
            result += "<div>" + user.toString() + "</div>";
        }
           
        return result + "</html>";
    }
       
    @RequestMapping("/findbyid")
    public String findById(@RequestParam("id") long id){
        String result = "";
        result = repository.findById(id).toString();
        return result;
    }
       
    /*@RequestMapping("/findbylastname")
    public String fetchDataByLastName(@RequestParam("lastname") String lastName){
        String result = "<html>";
           
        for(Novost cust: repository.findByLastName(lastName)){
            result += "<div>" + cust.toString() + "</div>"; 
        }
           
        return result + "</html>";
    }*/
//}
